version: "3"

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      - TZ=America/Buenos_Aires
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
